version: 2
jobs:
  build:
    working_directory: ~/music-from-my-tshirt
    docker:
      - image: circleci/python:3.8
        environment:
          DATABASE_URL: postgresql://music_from_my_tshirt:security_is_important@localhost/music_from_my_tshirt
          DATABASE_NO_SSL_REQUIRE: True
      - image: circleci/postgres:11
        environment:
          POSTGRES_USER: music_from_my_tshirt
          POSTGRES_PASSWORD: security_is_important
          POSTGRES_DB: music_from_my_tshirt

    environment:
      SECRET_KEY: ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            sudo apt-get -y install libenchant1c2a npm libgtk2.0-0 libgtk-3-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
            sudo pip install pipenv
            pipenv install --dev
            npm ci

      - run:
          name: deployment check
          command: pipenv run python manage.py check --deploy --fail-level INFO

      - run:
          name: check for missing migrations
          command: pipenv run python manage.py makemigrations --check

      - run:
          name: check code formatting
          command: |
            pipenv run isort --check-only
            pipenv run black --check --diff .
            find . -iname "*.py" | xargs pipenv run pylint
            npm run prettier -- **/*.js --check
            npm run prettier -- **/*.html --check

      - run:
          name: run tests
          command: pipenv run pytest

      - run:
           name: run end-to-end tests
           command: |
             printf "DEBUG=1\n" > .env
             pipenv run python manage.py migrate
             pipenv run python manage.py loaddata cypress_test_data
             pipenv run python manage.py runserver & npm run wait-on http://localhost:8000
             npm run cypress run

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results
          destination: tr1
